_wandb:
    value:
        cli_version: 0.28.1
        e:
            d1fl14q1utjhog0taeewmjog0othbh74:
                codePath: /Users/natedemoro/Code/MLE/intro/explore.ipynb
                codePathLocal: explore.ipynb
                email: nathanieldemoro@gmail.com
                executable: /Users/natedemoro/Code/MLE/intro/.venv/bin/python
                host: Nates-MacBook-Air.local
                os: macOS-26.5.2-arm64-arm-64bit
                program: /Users/natedemoro/Code/MLE/intro/explore.ipynb
                python: CPython 3.11.15
                root: /Users/natedemoro/Code/MLE/intro
                startedAt: "2026-07-24T22:26:19.010143Z"
                writerId: d1fl14q1utjhog0taeewmjog0othbh74
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 5
                - 53
                - 105
            "2":
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.15
            "5": 0.28.1
            "8":
                - 1
            "12": 0.28.1
            "13": darwin-arm64
features:
    value: pclass_onehot+male_x_3rdclass
model:
    value: RandomForestClassifier
n_estimators:
    value: 100
